name: CI Spring EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7 )
          echo "::set-output name=sha::$SHA"

      - name: Build maven
        run: mvn clean install

      - name: Build docker image
        run: docker build -t danielrodriguess/spring-eks:${{ steps.generate_sha.outputs.sha }} .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push image
        run: |
          docker push danielrodriguess/spring-eks:${{ steps.generate_sha.outputs.sha }}
          docker tag danielrodriguess/spring-eks:${{ steps.generate_sha.outputs.sha }} danielrodriguess/spring-eks:latest
          docker push danielrodriguess/spring-eks:latest
          
      - name: Update image helm
        uses: fjogeleit/yaml-update-action@master
        with:
          branch: main
          valueFile: 'spring-eks/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.generate_sha.outputs.sha }}
          commitChange: true
          updateFile: true
          message: "NEW: Update tag in values helm" 
